name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**/*.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**/*.md' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Install test-deps
      run: cargo install cargo2junit
    - name: Run tests
      run: cargo test -- -Z unstable-options --format json | cargo2junit > results.xml
    - uses: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'results.xml'
      condition: succeededOrFailed()
